### ISSUE TITLE
Umlauts in the file name

### ISSUE THREAD

**Issue by Bluespide** [focus-editor/focus#65] opened 2023-06-14 11:50 UTC
I have connected the editor to open for example json files. But if a file is called 'für.json' (with umlauts) the editor starts without opening the file. Drag'n'drop the file into the editor, still works.

**Comment by focus-editor** [comment] 2023-06-14 22:05
Is this on Windows? If yes then it's a known issue with the command line arguments being forcefully converted to ASCII with loss of information by the console. So what the editor gets is probably something like `f?r.json` so it can't open it.

Not sure yet how to avoid or work around this issue - any input welcome.

**Comment by focus-editor** [comment] 2023-06-26 03:04
Closing as duplicate of #80

**Closed by focus-editor** 2023-06-26 03:04 UTC
