### ISSUE TITLE
Viewport Scroll Stuttering 

### ISSUE THREAD

**Issue by Parzival-3141** [focus-editor/focus#52] opened 2023-05-28 03:55 UTC
**Describe the bug**
Scrolling starts stuttering after a second when using `scroll_viewport` key commands. Holding `Shift` a moment after pressing the key-combo prevents the stuttering completely.

**To Reproduce**
Open big enough file and hold `Alt-J/K or E/D`. You should notice stuttering a second into the scroll. Hold `Shift` a moment after starting the scroll and it should disappear.

**Expected behavior**
Scrolling should be smooth.

 - OS: Windows
 - Focus Version: 0.1.9

**Additional context**
I think whatever input code controls scrolling is using "raw" text input from the keyboard. Like holding a key in a text box, it fires off an input event once, pauses, then fires them in rapid succession. Assuming that's the case, switching to Key-State based input would be the proper fix. Just a hunch though!

**Comment by Parzival-3141** [comment] 2023-06-08 22:14
@obiwanus Sorry for the late reply. Here's a screencast of the behavior: [focus-scroll-bug.webm](https://github.com/focus-editor/focus/assets/29632054/f3740551-de8f-4d51-8028-af1a31c88b8e)
ScreenToGif's keystrokes are a little wonky, but note how it starts stuttering when it detects `Alt-K/J` is being held. I don't have `Shift-Alt-K/J` bound to `scroll_viewport_fast` either.

**Comment by focus-editor** [comment] 2023-06-09 02:20
Please can you attach your global config (and project config if you have it enabled)? Thanks

**Comment by focus-editor** [comment] 2023-06-09 02:29
OK I managed to reproduce it on macOS

**Comment by Parzival-3141** [comment] 2023-06-09 22:30
> Please can you attach your global config

Sure.
[global.focus-config.txt](https://github.com/focus-editor/focus/files/11710464/global.focus-config.txt)

**Comment by Sanian-Creations** [comment] 2023-07-18 22:27
@focus-editor What it seems like to me, is that the stutter comes from the editor receiving key-down events repeatedly after they are held down for more than a second. For instance, holding down the A key will type an A once, and then after a second it will start spamming A's. Try it: open any text editor and hold down a key, notice the behaviour.

I believe this is what happens when the scroll keys are held down, the behaviour is exactly the same. For the first second that it has only received the initial key-down event, everything is fine and scrolling happens normally, but after a second it continually receives the same key-down event multiple times per second, causing the stutter. 

This may not happen on every platform in the same way (and maybe on faster computers it does not cause any stutter at all), which is why it's hard to reproduce, but I'm certain that this is the root cause of the problem.

**Comment by obiwanus** [comment] 2023-07-18 23:23
I managed to reproduce it, so it will be fixed, just haven't got to it yet.

We do accept pull requests for bug fixes by the way.
(The smaller they are the more likely they are to be merged)

**Comment by Sanian-Creations** [comment] 2023-09-06 18:20
"fine, I'll do it myself"

**Comment by focus-editor** [comment] 2023-09-07 03:44
Please confirm that it's fixed now

**Closed** 2023-09-07 03:44 UTC

**Comment by ileonte** [comment] 2023-09-07 16:47
It's butter smooth for me on Linux now.

**Comment by Sanian-Creations** [comment] 2023-09-07 17:42
Nice. It wasn't lag by the way, just the key repeat mechanism resetting the scroll to start over at every key event. I guess it doesn't instantly start scrolling but smooths into it maybe? I don't even know, but it would do that over and over.

I feel like the scroll that follows the cursor when you move it up and down has a similar issue, compared to smooth scroll that also looks stuttery. Might look into that next.
