### ISSUE TITLE
Open file by name (ctrl+o): missing file items in current folder

### ISSUE THREAD

**Issue by maihd** [focus-editor/focus#104] opened 2023-07-20 07:24 UTC
**Describe the bug**
After open a file in another project folder, then use ctrl+o to open another file, the current folder doesnot display any file list items to select.

**To Reproduce**
1. Open a file in another project folder
2. Open `Open file by name` command box
3. No files items were displayed

**Expected behavior**
File items should be displayed.

**Screenshots**
![Screenshot 2023-07-20 141447](https://github.com/focus-editor/focus/assets/7189568/a805474f-7afd-485e-b3ae-c57669d5fcb3)

![Screenshot 2023-07-20 142238](https://github.com/focus-editor/focus/assets/7189568/35a9a50e-cf8b-47bd-9193-68244b7bde32)

 - OS: Windows 11 Pro 22H2
 - Focus Version: 0.1.10

**Comment by focus-editor** [comment] 2023-07-20 09:00
Just tried it and couldn't reproduce. 

1. Do you see the files if you navigate to that folder from the root (using Ctrl-Shift-O, for example)?
2. Are you able to reproduce it using a different drive, e.g. C, E or F?

**Comment by maihd** [comment] 2023-07-20 17:47
Ok, I will try it later.

**Comment by maihd** [comment] 2023-07-20 18:37
1. The Ctrl-Shift-O work fine
2. This is my screenshot from home PC
![image](https://github.com/focus-editor/focus/assets/7189568/159ac3b2-9c43-4309-a181-7c3de1ce455f)

Sorry if my description was not clear, or missing information. First, I opened a focus.exe without any arguments, then open a random file from any folder, then use Ctrl-O again, and this bug show up.

**Comment by maihd** [comment] 2023-07-20 18:39
Another folder in C drive, but work fine. How strange!
![image](https://github.com/focus-editor/focus/assets/7189568/41a8e942-2909-43df-a97e-0b4ae79670b1)

**Comment by maihd** [comment] 2023-07-20 18:43
More tests

**Comment by maihd** [comment] 2023-07-20 18:53
But I found another issues
![image](https://github.com/focus-editor/focus/assets/7189568/6f536c0f-1114-46b0-9bce-449accf2cbb5)
**Steps**
1. Open any file
2. Open file by name (Ctrl-O)
3. Remove a folder with `Backspace`
4. The file items does not be displayed

**Comment by focus-editor** [comment] 2023-07-20 22:05
I'm sorry, it's been a while since the last release and I forgot that this issue has already been fixed in the main branch - https://github.com/focus-editor/focus/blob/2047a6afe9bf092e873cf74b24baa1fe675a3a19/FOCUS-CHANGELOG.txt#L42

If you're in the beta you could compile a more recent version. Otherwise I could give you an executable if you want. Hopefully it won't be too much longer before the next release.

**Comment by maihd** [comment] 2023-07-21 02:32
Tks, I dont have the compiler. So, I will wait for next release.

P/S: Your design is very good, have the good ux, and very clean.

**Closed** 2023-07-21 02:32 UTC
