### ISSUE TITLE
The editor takes long to open when placed in a subdirectory in drive C

### ISSUE THREAD

**Issue by CELLTH** [focus-editor/focus#217] opened 2023-11-12 21:19 UTC
**Describe the bug**
The editor takes a very long time to open after launching the executable.

**To Reproduce**
- Place focus.exe in a subdirectory under C drive. e.g. `C:/bin/`
- Launch the editor

**Expected behavior**
The editor opens... quickly 

OS: Windows
Focus Version: Nightly-dev (12 November, 2023)

**Additional context**
Taking a guess that upon launch, the editor is scanning either the contents of `C:/bin` or `C:`

**Comment by focus-editor** [comment] 2023-11-17 21:44
Can't reproduce using `C:/bin` and it seems that the issue is most likely to do with the temp folder rather than the executable location as discussed on Discord.

Next time this happens, please can you check the contents of the temp directory and tell us how many directories are there. It should delete old directories, but maybe in your case it doesn't, which could potentially be slow if the list grows long enough.

**Comment by CELLTH** [comment] 2023-11-17 23:26
Yeah can confirm that the temp folder is causing the issue. I have archived a temp folder that consistently causes the slow launch. I have checked the folder and it contains 21 folders. I have attached the temp folder here, if you place it next to the exe file, it should cause the slow launch issue.
[temp.zip](https://github.com/focus-editor/focus/files/13398200/temp.zip)

**Comment by focus-editor** [comment] 2023-11-18 00:45
I've tried it with this folder (nightly Focus from 17 November, 04:06) - launches fast. Even tried it from `C:\bin`.
The folder looks ok, the number of sessions is as expected.

**Comment by focus-editor** [comment] 2023-11-18 00:48
It could be something on your system that slows down things. Maybe an antivirus or Windows Defender? Have you added the focus folder to the Windows Defender exclusions?

**Comment by CELLTH** [comment] 2023-11-19 10:46
Yeah I have the focus folder to the defender exclusions. I just tried to replicate this issue in a Linux VM and it doesn't happen there at all. This is quite odd, and I don't know for sure what's affecting this. On my Windows machine, if I try it with the faulty temp folder, the issue happens almost in every single focus launch, regardless of the executable location.

**Comment by CELLTH** [comment] 2023-11-19 10:48
If you want to investigate this issue further, I'd be happy to help. But I'm not bothered too much by this as I found the culprit and can easily work my way around it.

**Comment by focus-editor** [comment] 2023-11-19 16:56
We will definitely investigate, just busy with other things right now as we need to finish the build system and do another release first

**Comment by CELLTH** [comment] 2023-12-11 01:28
Just for the record, this bug started happening on a new PC as well. Albeit more rarely.

**Comment by focus-editor** [comment] 2023-12-11 01:51
Thanks for following up on this. We'll reach out when we're ready to investigate further

**Comment by CELLTH** [comment] 2024-02-08 13:07
This issue still persists. Any chance to take a look at this?

**Comment by obiwanus** [comment] 2024-02-08 17:24
@CELLTH any chance you could run the debug build of the editor (available from the releases page) in a profiler like Very Sleepy and show us what it says about the time spent at the startup

**Comment by CELLTH** [comment] 2024-02-09 10:06
[capture.zip](https://github.com/focus-editor/focus/files/14220269/capture.zip)
Yeah I have recorded this capture where an instance of the slow launch appears.

**Comment by focus-editor** [comment] 2024-02-12 17:48
@CELLTH how long did that launch take exactly? Also, looks like you didn't include all threads in your profile so there's nothing in there that takes a long time.

**Comment by focus-editor** [comment] 2024-02-13 23:27
There's an option somewhere which says profile all threads

**Comment by focus-editor** [comment] 2024-02-20 23:48
@CELLTH one of the captures suggests it might be due to the file watcher. Please try this build with the watcher disabled and see if the problem is still there - https://drive.google.com/drive/folders/16akMNqEJmfuY2FX6KrbmFLhieMdxzetv

**Comment by focus-editor** [comment] 2024-03-05 18:42
@CELLTH please try this build https://drive.google.com/drive/folders/16akMNqEJmfuY2FX6KrbmFLhieMdxzetv?usp=sharing

We have another theory on why this was happening which should improve things somewhat on Windows

**Comment by focus-editor** [comment] 2024-03-06 21:52
This build is not fixing a crash, it's about the slow startup time. If you're going to be using it you'll probably be better off downloading the latest nightly release build, because the one I sent you is a debug build

**Comment by focus-editor** [comment] 2024-03-07 19:31
Nice, glad we've finally resolved it! It turned out to be a single Win32 API call that turned out to be super expensive on some systems.
Actually before I close it please do try the debug build I sent you and use a temp folder with at least 20+ sessions to confirm it's really fixed. 
In the main branch I've also bumped the number of allowed session directories to 50 so it's possible that when you reach that number it might slow down again.

**Comment by focus-editor** [comment] 2024-03-07 20:06
Cool!

**Closed by focus-editor** 2024-03-07 20:06 UTC
